export const VISUALIZE_DATA_INIT_DATA = 'VISUALIZE_DATA_INIT_DATA';
export const VISUALIZE_DATA_SWITCH_TAB = 'VISUALIZE_DATA_SWITCH_TAB';
export const VISUALIZE_DATA_CHANGE_DURATION = 'VISUALIZE_DATA_CHANGE_DURATION';
export const VISUALIZE_DATA_CHANGE_TIME = 'VISUALIZE_DATA_CHANGE_TIME';
export const VISUALIZE_DATA_SUCCESS_DATA = 'VISUALIZE_DATA_SUCCESS_DATA';
export const VISUALIZE_DATA_FAIL_DATA = 'VISUALIZE_DATA_FAIL_DATA';
